// NexTV Service Worker v4.0 — Instant Image Cache
// Pre-downloads ALL 366 movie posters + backdrops on install.
// After first visit, every image loads from device (0ms, no network needed).

const CACHE_IMG    = 'nextv-images-v6';
const CACHE_STATIC = 'nextv-static-v6';

// Every poster + backdrop URL in the entire app
const ALL_IMAGES = [
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/xJHokMbljvjADYdit5fK5VQsXEG.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/hkBaDkMWbLaf8B1lsWsKX7Ew3Xq.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/s2bT29y0ngXxxu2IA8AOzzXTRhd.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/ApiBzeaa95TNYliSbQ8pJv4Nj6M.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/bOGkgRGdhrBYJSLpXaxhXVstddV.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/d5NXSklpcvweasTZTdgw9J6tQj7.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/jYEW5xZkZk2WTrdbMGAPFuBqbDc.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/avedvodAZUcwqevBfm8p4G2NziQ.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/fZPSd91abroad5JeYDp4hgaGhMx.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/umC04Cozevu7nn86uBnMmn3T7oT.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/iQFcwSGbZXMkeyKrxbPnwnRo5fl.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsLYHufncOHgx.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/tmU7GeKVEMrBleo5ycVBFurqvxJ.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/62HCnUTziyWcpDaBO2i1DX17ljH.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/AkB37EMGilAN21h0CAQRP2hKzDc.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/jRXYjXNq0Cs2TcJjLkki24MLp7u.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/o0s4XsEDfDlvit5pDRKjzXR4pp2.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/6WBIzCgmDCYrqh2sKwcMdVbGgSD.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/ncEsesgOJDNrTUED89hYbA117gg.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/f5F4cRhQdUbyVbB5lTNC1F0FYzO.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/87hTDiay2N2qWyX4Ds7ybXi9h8I.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/loRmRzQXZeqG78TqZuyvSlEQfZb.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/pIIskHRyB9SiNTpsx1Q0Ya2TUDU.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/iuFNMS8vlzsOne7rlNsdNYWzWWT.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/nHf61UzkfFno5X1ofIHQ4lnxITX.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/k7eYdWvhYQyRQoU2TB2A2Xu2grZ.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/4NxCDWJ7FXfVkldHnNsQaVqk7VE.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/zqkmTXzjkAgXmEWLRsY4UpTWCeo.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/uxzzxijgPIY7slzFvMotPv8wjKA.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/b6ZJZHUdMEFECvGiDpJjlfUWela.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/ggFHVNu6YYI5L9pCfOacjizRGt.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/x2LSRK2Cm7MZhjluni1msVJ3wDj.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/rcA37ys54PssDn9rHALMzOtChbW.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/u3bZgnGQ9T01sWNhyveQz0wH0Hl.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/suopoADq0k8YZr4dQXcU6aLJ3a.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/6Wdl9N6dL0Hi5T4thkizCvrkTkM.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/dDlEmu3EZ0Pgg93K2SVNLCjCSvE.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/qw3J9cNeLioOLoR68WX7z79aCdK.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/vUUqzWa2LnHIVqkaKVlVGkPaQca.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/wiE9doxiLwq3WguhPef0bT4fLc.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/apbrbWs2BerzUCMBQl7JFHv00If.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/nMcayvRnSGcvtOxCAC7ELvDHBHC.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/reEMJA1uzscCbkpeRJeTT2bjqUp.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/xGexTKCJDkl61ljM3dB0CxLyGKm.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/hlLXt2tOPT6RRnjiUmoxyG1LTFi.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/6S8XKQD5k17cSmpFMSJT5MnGJJy.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/z2yahl2uefxDCl0nogcRBstwruJ.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/etj8E2o0Bud0HkONVQPjyCkIvpv.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/7vjaCdMw15FEbXyLQTVa04URsPm.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/jBJWaqoSCiARWtfV0GlqHrcdidd.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/n7PgcnYRqRNBSKwP4UkuCirr4Ly.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/x4OJAjXFNJ6GfFRZXU9tLrr0HKo.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/iigTWBRGk3QxAnRCEsNVXpSJWPs.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/aDLMHI9oBPdRiF8aSgTHSVgM4Sk.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/hTP1DtLGFamjfu8WqjnuQdP1n4i.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/iy5EKOlVleRHZwTaEjYgQH7JurC.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/xUfRZu2mi8jH6SzQEJGP6tjBuYj.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/qEcg0kbMdPtqPBGVdQQGCRtBRGf.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/5ZFUEOULaVml7pQuXxhpR2SmVUw.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/ypbHt24SjoMidFfCX3Lk8aDEgK0.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/xppeysfvDKVx775MFuH8Z9BlpMk.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/BtOe6Jvzp50bCk96Mf1WBKI3s5.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/e3NBGiAifW9Xt8xD5tpARskjccO.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/2rmK7mnchw9Xr3XdiTFSxTTLXqv.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/B7N7IOAFY3l8bFI0OwSxKyXBkDU.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/geGm4zkFCJi1SoFJnhCUrUZ02mO.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/1ZdED4PBsFF1dtHJDfmTYbGrpMZ.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/pebZ1ZKRX2XYJzRU4YIAFxDELIn.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/oiPTEJfJExILFdEVhJg36NiYRaD.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/bO3s5IOJFZq6V9P4E9vfR5HyOFP.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/3AS8MLKXJ7vOTlvCJiXjmePuLq4.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/o5i88FtLSdnYUDnJGiXlEEiRFMF.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/2EewmxXe72ogD0EaWM8gqa0ccIw.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/hW5FHE6NBZSE4u5HcMaW3GeHerD.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/1enwEQVgBKy9lekSXSmXPCODJ6z.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/mCPW4QgCeNJE4MELSUVUNxPaEhL.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/cKhSgBzKQ0gPRQJXIBnrwQg77cF.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/orIt9gFdJaRuXNnrZBsBRMEr4y9.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/gdIrmf2DdY5mgN6ycVP0XlzKzbE.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/vBHgEMfCiAJ6lGkJMlUe5DTzklQ.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/2IWouZK4gkgHhJa4PPBn6VqAGRD.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/xmrRrQ9LjnCeaEkFyKXGaGwGBGF.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/sCx7FEFEanHxT4pSLSJjTNRJEQu.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/axKqalBXTnrKUF3R0jL7DnvRMPN.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/qXthUuaFGmQQJMXXhMMBBumQU65.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/rNFSmYXHdEMHJjrGzBRgvsKbUNk.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/qcOBTMOBBJSjWGKoXJ3dtABH8mb.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/8NsHFBNJi7GNFNlumMFvqFZ1s3d.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/q6Fh3VE62RXGC2FhRJ94q2FZXoR.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/aOOYCpqBYtWWTBa9JN7KGPiMXp7.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/7du3sLBjbCUTRoGnLfAHLrBsJb4.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/AbbXspMOwdvwWZgVN0nabSe1T0.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/nxxGhGVGzOhLIdTOxIHrqikLKsU.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/wge0gxGmXHmxrxFc4GYWi4ZFhKj.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/js9e6CKEUbVFVFyAMWOViqDfuEW.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/sgheSKxZkttIe8ONaJSoLRbBMbS.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/mBBMBOvqdyX7ckSoaLHnRhb6C4y.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/2zh9YBPdGVHXGQ1JC1Rlnc2TDYZ.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/r6gpH4VMRmhb4PkLdREiCTfCMqC.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/w9kR8qbmQ01HwnvK4alvnQ2ca0L.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/zGLHX92Gk96O1DJvLil7ObJTbaL.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/pSgXKPU8gFHlbDNp8zLnbxWMBqp.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/2Pjx6fMpZJFb6eVMlgQ9ydnvtCj.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/casOvHEJ8mkEZRR0U0oScaEhNKv.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/nD7vNDEjhlmcN0TDPpCMRmOTkMg.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/RYMX2wcKCBAr24UyPD7KE3wYQly.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/o0iwhT2YERWHQHuaKNpnEYNAGPP.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/f4J9W0UvGJJ7bPBXnBWxHNvDuOj.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/sg7Dp5mjz2qbXJMsyYEA3V8sTGv.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/9TBD4QJKGJO7YMGBBTM0YSDBF7N.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/wFqVLtBFhpQM3ys2XOSD3EOIJTW.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/yDHYTfA3R0jFYba16jBB1ef8oIt.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/yrpPYKijwdMHyTGIOd1iK1h0Gu8.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/rOmUuQEZJHGGkFAqNQoZbKHOSHG.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/wWba3TaojhK7NdycyUDVhg0bjnc.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/lgkgWvKKXHo2OXcC53tGGNzDZPe.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/kDp1vUBnMpe8ak4rjgl3cLELqjU.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/b33nnKl1GSFbao4l3fZDDqsMx0F.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/9SSEUrSqhljBMzRe4aBTh17LP9Q.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/hA2ple9q4qnwxp3hKVNhroipsir.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/phszHPFBOef6PCOoMkiKSmwBVRx.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/xRWht48C2V2jDSxqfAbKQkiCGaJ.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/aQXTKkYJNFgCfHfqnUwBBdmHaEX.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/s16H6tpK2utvwpaS2fnSLGqFnEI.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/kuf6dutpsT0vSVehic3EZIqkOBt.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/AmR3JfKAMJJ74JGnunERQQzd2jA.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/sv1xJUazXoQuIDfyMqkfM5uXUUN.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/xDMIl84Qo5Tsu62c9DGWhmPI67A.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/rjkmN1dniUHVYAtwuV3Tji7FsDO.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/70nxSw3mFBsGmtkvcs91PbjerwD.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/oBgWY00bEFeZ9N25wWVyuQddbAo.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/vXHDFKNWZ4Tlxs1e16WQvnzANfT.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/zAYRe2bJxpnMlSlAGCfMjSbnEbO.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/dE2DPBvJMzXJNkIiXBifnTMHVIp.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/4xgl3yw5eFMCBSXKE8KyrHxBSmA.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/laTbFqjOWLdqMZNhH3eFqN0mwrI.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/bE4MyDNjUUSLmSbZSmFOjLDFqTu.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/9hvhGtcsGhQY58pukw8w55UEUbL.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/wMLSMHYOXlgFGt0sH3QlQfBCoaH.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/lfRkUr7DYdHldAqi3PwdQGBRBPM.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/vW0rFCUQRYsMEkTaqUjPBMVr6k3.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/ySSgoMVALAipyOIr0JVHHXiQKuT.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/npdB6eFzizki0WaZ1OvKcJrxmd.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/jM6IPsYhHkRgJwxlqZyRCXqMVIK.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/gQkCPfn6GGMuHfzGQUHI5GKUMOH.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/odzc3Xpxgw3EjJC1XVovDHzFcqw.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/vXuapjMVqFEXHM3HcTJpfakdmf5.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/n1aAsHnFQRSHPHPLPm0oVzQYJrl.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/lVg7IFgCoaCqOj2BbBpUhTsXFE5.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/9P3GmKIhVnSJfDM4cGVApJBQ9mK.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/qbFc04EKKx33VoqxRqsEW98c5IG.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/kHb7hzVH7G1RJLY3BTF1l3sDAbo.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/7wp1nyJ5GxmZBFqXd3GCVDB1DuG.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/rrAMByTJwLDjNl9rRFmjhMbCsNN.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/sKVSBptUfE0sRIYzJ2DWHFcfmwl.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/lXBSeZkqRoNpCK5q9CcCPvTLfKD.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/miqvB1YPqaFkWHlJpvoRYHgHBBO.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/8Rl7lSnPqMY5GKdQPALcJy7SNCJ.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/9SgDSFhFGELNi6A5HmaxVBN7DtT.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/uRuFh34KiEPBRKcBdVXVTEkuasM.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/h8Rb9gBr48ODIwYUttZNYeMWeUU.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/9BNLBBQpKKjRTqWzRVzJH3JJyBY.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/nzoRMYDC8RFqRj3OLiqDn4yJaFo.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/zJoB3RZFJQsFhLuDHsOhh4UKSsX.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/sT7KmGAz71D6dX0jKBgCRKpjH5I.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/axXSBq9U6AZyCMFHnDhKqQJ6nMB.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/gAoXVB08qh4AkMKGtlXj8nuiX6n.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/sFTFVSS7d5bkGJfLgBvZKUc5Crt.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/4Uqn1osT8RiuCXFIBhBkzLrb1Fq.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/mkhBh9WKgRp8dHu09V5MkOoNvYk.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/4m5MiZVuVnIaS7GUQEYnBnRJeLP.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/bS4DB5HLXKR7pbN2MOXN0cBW1KR.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/aLVkiINlIeCkcZIzb7XHzPYgO6L.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/tElnmtQ6yz1PjN1kePNl8yMSb59.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/2cxhvwyE0RtbS6MLjCWCJBsDOij.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/euYIwmwkmz95mnXvufEmbL6ovhZ.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/wTnV3PCVW5O92JMrFvvrRcV39RU.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/417X5AeZPMDaHgTGeSSSmOHpGhX.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/8b8R8l88Qje9dn9OE8PY05Nxl1X.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/k6RlxBiMqEQpxXSMfELgHa6Fmhb.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/llQSa4pJhKHUG9Z4qfGOF0RGQLY.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/fiVW06jE7z9YnO4trhaMEdclSiC.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/4XM8DUTQb3lhLemJC51Jx4a2EuA.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/ym1dxyOk4jFcSl4Q2zmRrA5BEEN.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/8YFL5QQVPy3AgrEQxNYVSgiPEbe.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/51tqzRtKMMZEKesPMqyx3MZtBBV.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/74QLIJkBGTQ8JW9CItQ8iiOLXnL.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/bkpPTZUdq31UGDovmszsg2CchiI.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/cVhMgSAEzM5LhrwGXqe0a1cDPnb.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/Af4bXE63pVsb2FtbW8uYUyIxoKr.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/4fEFc7IpJBGsLWkfmm0e8UXSB4R.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/A4j8S6moJS2zNtRR8T9oKkzODRO.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/5S1QfC8JjO6fJvHBucCbIa4pxsH.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/vBZ0qvaRxqEfnuDdBLQPFgBRGmm.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/uS3G2lSMwlPgfOdKnXBQnvXNqkO.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/bcM2Tl5HlsvPBnL8DKP9Ie6vU4r.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/b4SFzIqzKh5KWyV2jCPSU0oyCLf.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/cMBflAbpFpFNFCHYFAkEUoEUaQ4.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/mDeWuRPBUaH7RanrI6JKc0QjlB5.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/lurEK87kukWNaHd0zYnsi3yzJrs.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/2NN0n7yTETEslbgW5h6HhJDLrSY.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/A7EByudX0eqqArGmgIncgCphTcd.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/xTHltMrZPAJFLQ6qyCBjAnXSmZu.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/xg27NrXi7VXCGUr7MG75UqLl6Vg.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/gPbM0MK8CP8A174rmUwGsADNYKD.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/bz66a19bR6BKsbY8gSZCM4etJiK.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/kdPMUgzOmjOhNjkS2qkJLjmJvnB.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/nQt0RFRlkNTJeqYm2CqD9oQ2v4H.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/NhvMBrCVXfkmFtxmCeL6Jfkztb.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/couKeU8Lak5ztB7unP6hXWnCtCR.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/bUbUzQJo0e0kXfVzLsqVWzqE2Jg.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/xlbFYMBiRBFbFsghsJB2LNJhXAD.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/llGFnzY32sHnMAlpMxTuJORFMla.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/l9cCQBCHE6hbAyJZfxRIx9LoRSQ.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/8LxFo5pXNWrBFKYMRnBjmHxX9Qb.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/cuAMRObhJnEXXBgMbxpiFKqVMVa.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/dOk20BptRuiMGqbBwQVFvY30dT4.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/heqL10ctf8lR0uqlZmBVmwT2M3G.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/sOQHHSSjlVSGK4sMqBB49sBmOAH.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/lmBGFfmHTqRHBYRVrZ5LzDx7gSb.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/lJA2RCMfsWoskqlQhXPSLFQGXEJ.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/jC1KqsFx8ZyqJyQa2Ohi7xgL7XC.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/a1VRXlaQMuPY8DgubnHLMpQmJWV.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/jb8fMQjxnJuLRD9n5jSQVCbKSU6.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/fqldf2t8ztc9aiwn3k6mlX3tvRT.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/xtgP8oSfNAYFdnHRpBvbSSvFCcj.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/6POBOQMBBpXpIBmynOGGJuYYbrj.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/gK8cqlGLpJEcTnP5ZGHorhkHdaS.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/4ueALR19dSxBxrKLi3vPAXXdGkZ.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/3VVMOObwHQtQxPpuFJGqNJa0T6V.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/e4aqizYCues4kUBEouUsixrFwC8.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/vNCn2X0HxnWPL2li8ANuQjU11uQ.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/lMBGBVJNhVkJ1VJHKw09y6qqGP0.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/jvYqcOFtCLN3DCZB6cFg2UBUePP.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/8InPf9MjYZEU1FrLNlUl9qzDmn7.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/xEKhRDEJFnkMYfpAQOJjX4AHvnj.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/cEFGCBTXOQHbDwnVLfxhPjAbBkH.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/6xyJnfkEJJ44sJGSmNPBW8iV6lA.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/wOOm0PAB8fMIH40QSX15n0ixRqQ.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/6MKHPzIkGBsA68zF4CjyGBXYH4Z.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/jq8eRKK7tEz8iFkMpHGjGJ3HaVN.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/59OSp0YRNpM7dL8SriYS2I8e3aW.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/vxbXJqOEOzx6Wb7JJ39tYjIPTCL.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/gxBgdGz0RuWNJhkmf5c4MzECFmO.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/1wSGMaGtfkeSMmEOnDXjVkKuWwb.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/hr0L2aueyklP2BYQ5nMSuf2CTKSM.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/kEtQFBMcFOuIFLRqSF0eKdJqkGI.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/34m2tygAYBGqA9MXKhRDtzYd4MR.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/bMFMgJORHgFSFOpivW8oedsqMDg.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/kSf9svfL2WrKeuK8W08nb9RKge4.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/ilRyazdMJwN05exqhwK4tMKBYZs.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/btgCArMFNTzZbOGlJ2ekFz8gBfG.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/2O0jJBKBMCVFhWRHRXAYmpLF4C4.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/6zUiTjXxMj1cIUr9bU9YxGrqpBH.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/sZmcGPeODXnECXeVIjXvBz0CJXJ.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/r7vmZjiyZw9rpJMQJdXpjgiCOk9.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/bHarw8xrmQeqf3t8HpgEJSFSs9I.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/n0ybibhJtQ5icDqTp8eRytcIHso.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/lktCmDzTKIlMgZcnrjNDN57XMRo.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/tMefBSflR6PGQLv7WvFPpTKpYm8.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/9vNrr0NS8WLlVkHXKXFD2bBVQ5h.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/6nhCs8K29HVUQPozNBBFXtNFAmf.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/4TKUDkxHmtQj72bOZe5tdhUhBSS.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/kAVRgw7GgK1CfYEJq8ME6EvRIgU.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/gg3ztnpNRuHnmLQ0MZbFn5JhMgQ.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/6DrHO1jr3qVrViUO6s6kFiAGM7.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/vJAgzMEHr6IhJ0fKgFJvnAF3BsF.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/uo4pKRBWKHBJb1IkLbKxsNVFoGe.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/yDWJYRAwMNKa9MBdPJOoFgMX3vg.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/6UH9YKsHKtjXnCflq1jfhMKIhFd.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/tP3GAFGxMSuNBGJRpJDwFzRyTxS.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/7QNFGj3gBzLERQOtBD6VGvXHLRo.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/vd9VJPmL82JhXfKU7Xu8kfxwEiR.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/7QPQLC2ZPEUzLbVcJf5nLGPOjPE.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/3LqFfFAFqovl0l0mBRLFGKOgRZK.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/3LqFfFAFqovl0l0mBRLFGKOgRZK.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/jgE3GlPVQDdp20o7kwGMEqBBSBT.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/1LE6Mk0qSW1OWVdRHgVS0wMMUvl.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/7DnXiVCXFxnJKDCpMa4xFkSrMXU.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/hKt4FOzEVVDN4O3BGPfFJxWiLgd.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/c1n3JtOAPNJhMGCYgaV6HbIl5N5.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/qnGMnGeomKP9ADRa18H0q0RBh0e.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/4fLolCzEhFuJklKr0a26DziqsVj.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/5mHPNGGPExKxcuKsA29C7Ys3O0R.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/RYMX2wcKCBAr24UyPD7KE3wGBnX.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/kwJOZCbr5T4hJTDGPpzBHFSuNOM.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/78lPtwv72eTNqFW9COBYI0dWDJa.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/cyecB7godJ6kNHGONFjUyVN9OX5.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/xmbU4JTUm8rsdtn7Y3Fcm30GpeT.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/8Y43POKjjqZptVdMTiuSBT0CIhJ.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/iUgygt3fscRoKWCV1d0C7FbM9TP.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/1953j0QEbtN17WFFTnJEKWQiOtq.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/r2J02Z2OpNTctfOSN1Ydgroma84.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/5YZbUmjbMa3ClvSW1Wj3D6XGkVA.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/ckMfVAoIiRdPRsz2t8xHYoAp2YC.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/f8dAnpmyjGAVbLm4VdmN0IKI2VD.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/3rBBSIf7QBMV7iVVRYBrzXFDFZ.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/9mFPFb2hD1jXAMbbBjfqWpxRTAT.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/88BFJpL4SbxeLjg3LoAHv5Xp9pX.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/hRuWLUyiOHEpkxvhHuOCO8LoT4z.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/e3LlPOGMoJ5gC3TtNGWj5i1BxA8.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/9c3T7PZCR6mGD3vvKxKYlvhQ2qM.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/4PCHRzfaaTh7AcPBXxMtJaO8wr1.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/9QVkfwSvC67Gca1eG2nTNcLxLJ0.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/iCiSqhMoFgNnDFcmGZa0LCqFl0B.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/n3MCBCEf6qm7qjWX1IXyWWVpijI.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/kSXLQeHLIlX3o9fIPNEQhgRjnnH.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/6HECaYOOQUfS3NJbN3R9z7oF2iX.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/9VwFQbRuBHBfFvk0aXAJKYL2KIK.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/tPB5y3uXJLb8RLQP1Yw3HcJBVqR.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/mLyW3UTgi5BjwBBqAkLJlqm5w3s.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/7MBPDGtJkNzNXBBqGDsxEeNTJWp.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/2SqJGxuNF4KbLiXHBv4fSZGBmNn.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/l8ORFLWXsm6abyxHhbqJwTkDIxR.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/jChkIQtNWvGv4FHJeJDBFbezHBW.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/tvfnLIFTVCfCEdBipuSoWe8b5Vn.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/2IWouZK4gkgHhJa3oyYuSCnGqSB.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/yMrOmRcmQJPxrJU2HcqrvqDgHEf.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/w4uYVfPP0fTBQKJSqBKhIqSVH5.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/cFJpFSoiJxQUGWGCjblqZmhzqLM.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/3FtAfGRMrAw2hNz8hY8ADNjQsJX.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/bkAuEGMEq3ikMaenFzSNO1Rmxdb.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/cRaGFzYuoU6p6LBdxjgFCXDG4dM.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/vhk3LTv6kQ2eMHVPMJhNKKhQJVS.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/ylgBDIxJTgxhv60OQ8XrUHpxkZP.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/8MCzHJDYJuNVHqkXdTW79y9hbTf.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/qkhkpBFrPb8ZA6MVAIGMsqT9Dld.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/m8dB1F1U8g95bz3tBUqmilCxPvF.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/7IjM5r4PqIh0gJDTLZkCIGTcOnZ.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/d0kxRa9Q1RPuCDKZ5vNJfk5Q5nG.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/4g5MbMmYbr4Vb7vELMksTzJhv5i.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/u1M1RSq7VQtJERGvb5n0YJuvGTh.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/kBT0KJiqEkAoD5TS3a3lOkGFrHA.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/rP6gsPEdDGanpjSXgwzuHQCRmXl.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/cUnvY3rRCkFDnkNQoxTSHDUBE.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/s16H6tpK2utvwpaozGhAlp6VYd1.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/Ag3D9qXjhJ2FUkrlJ0Cv1pgxqYQ.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/rktDFPbfHfUbArZ6OOOKsXcv0Bm.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/yF1eOkaYvwiORauRCPWznV9xVvi.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/8xV47NDrjdZDpkVcCFqkdHa3T0C.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/4Y1WNkd88JXmGfhtWR7dmDAo1T2.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/stOhMIFKHHPpHGe2grFl1AAtPNJ.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/8rpDcsfLJypbO6vREc0547VKqEv.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/e2MSmsOSAA6k0pWdmMoEBXqMlMV.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/d4fECd7E3T8E7NnMJJkO2wfNqUv.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/4A5HIOmMhvT0AeVD4EOBhkJ3oVl.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/hkxxMIGaiCTmrEArK7J56JTKUlB.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/pA3vdhadJPxF5GA1uo8OAiZSqvW.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/Af4bXE63pVsb2FtbW8uYuxU67KF.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/4K7gQjD19CDEPd7A9KZwr2D9GMS.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/NNxYkU70HPurnNCSiCjYAmacwm.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/1E5baAaEse26fej7uHcjOgEE2t2.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/dB6jOvZsHSIsaGKLtCFB43AQHSW.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/1X7vow16X7CnCoexXh4H4F2yDJv.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/kdPMUlCOHrob14eTxvCUHxzGpZZ.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/gMJngTNfaqCSCqGD4y8lVMZXyfI.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/qhb1qOilapbapxWQn9jtRCMwXJF.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/jtAI6OJIWLWiRItqi19wBiFK9wC.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/7GpZqAQfVtMjMYAbJHHtEGMFvkU.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/Aph9Qb37y2XAMHhSiC3DGeQYFJk.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/51tqzRtKMMZEYUpSYkqpy7gBr0O.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/4m26ZDIzUzBEWHmGnfFgLpQaRwK.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/kEl2t3OhXc3Zb9FBh1AuYzRTgZp.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/rrGFZJ6UKuDmFi3ZMGbHGaFUijP.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/3Q0hd3heuWwDWpwcDkhQOA6TYWI.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/1LRLLWGvs5sZTMSMgHAMkxNJgCt.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/stTEycfG9928HYGEISBFaG1ngjM.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/mGVrXeIjyYPWGDmU0qzfjBFzklM.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/1Ociiqn8jgwBE7mOQlAjOuBl6Kx.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/f8JaHvDjzW2KQLVN2DwMVuIwwxh.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/9PFonBhy4cQy7hjTLtQ64FhogCl.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/iHSwvRVsRyxpX7FE7GbviaDvgGZ.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/pCGyPVrI9Fzc6mMEnCLBmCGpnXF.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/87k6O0qlurLnHOm9Ltc3Xa7MTJR.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/9vuFPTNYkuWwRLzAMiKi2LxVSI6.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/lOHxDr1F1jXAq2GshJLLWrOxnDH.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/59SVNwLfoMnZPPB6ukW6dlPxAdI.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/llGQxOv9Tqf8sepoFN1dyxFTSaw.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/8D3oujCiKo7WVTB4VBnUMEtZmFZ.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/iDb7DuBzPkdB3QsuFcLJDdLFQT1.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/lX7sXNPcF1ydQAqUe1pJfQZNwxn.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/zAY1N1SBXc1pHPGQMBZdU6VtpHm.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/2ACtTqPDwSIMHg73xGhL3UBf7t2.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/fcXdJlbSqiIku76fkCiHh2QHmZx.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/npdB6eFzizki0WaZ1OvKcJrWe97.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/xWIlBMnO3L3ot4JTr38hbGt0NAp.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/vSQIpPEYbBQ49cBqnAel3ILTDOT.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/5fhEJ5DlWUCQTHPdVHbkQNfPmGE.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/msSweZnNQTBQLJMtqftQrojBNJW.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/8MhKNKDmWGlrRMkAovJMxkONzB5.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/3Yb3cCkq9EcgzLxIAFTM5mVGWEQ.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/fHgdVHQNgAnZC9ZXOQ3LnIXCCdS.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/l4IEBrMxVMFoMLVFzYJqSLKMHlq.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/xfIVBHilGGWz7Q0nmMFKRg4aVBG.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/nQJJMzG7Rq9AkUvTqYXkJzVxMHl.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/cHBCPgmBbcHkrVhW4JIo2PG3Eq0.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/3FZnCJVzZUNVj7FXPJSuXNrHVEp.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w500/dJKmkh6DVbgVDLpJbfCDkiZPXoM.jpg",
  "https://images.weserv.nl/?url=image.tmdb.org/t/p/w1280/8VqDH9RJpBnLGS4yEjbWbkCnOa7.jpg"
];

const STATIC_SHELL = [
  '/index.html', '/style.css', '/app.js', '/db.js',
  '/movies.html', '/series.html', '/anime.html', '/cartoons.html',
  '/search.html', '/watchlist.html', '/profile.html', '/watch.html',
  '/history.html', '/genre.html', '/filter.html', '/404.html',
  '/get-app.html', '/manifest.json',
  '/icons/icon-192.png', '/icons/icon-512.png', '/icons/icon-maskable-512.png',
];

// ── INSTALL: pre-cache everything ───────────────────────────────
self.addEventListener('install', event => {
  self.skipWaiting();
  event.waitUntil((async () => {
    // 1. Cache static shell
    const sc = await caches.open(CACHE_STATIC);
    await sc.addAll(STATIC_SHELL.map(u => new Request(u, {cache:'reload'}))).catch(() => {});

    // 2. Download ALL images in batches of 15 (gentle on network)
    const ic = await caches.open(CACHE_IMG);
    const BATCH = 15;
    for (let i = 0; i < ALL_IMAGES.length; i += BATCH) {
      await Promise.allSettled(
        ALL_IMAGES.slice(i, i + BATCH).map(async url => {
          try {
            const already = await ic.match(url);
            if (already) return; // already cached, skip
            const res = await fetch(url, {mode:'cors', cache:'force-cache'});
            if (res.ok) await ic.put(url, res);
          } catch(e) {}
        })
      );
    }
  })());
});

// ── ACTIVATE: delete old caches ──────────────────────────────────
self.addEventListener('activate', event => {
  event.waitUntil(
    caches.keys()
      .then(keys => Promise.all(
        keys.filter(k => k !== CACHE_IMG && k !== CACHE_STATIC)
            .map(k => caches.delete(k))
      ))
      .then(() => self.clients.claim())
  );
});

// ── FETCH: cache-first for images, network-first for pages ───────
self.addEventListener('fetch', event => {
  const url = event.request.url;

  // IMAGES — serve from cache instantly, fetch+cache if missing
  if (url.includes('image.tmdb.org') || /\.(jpg|jpeg|png|webp)$/i.test(url)) {
    event.respondWith(
      caches.match(event.request).then(cached => {
        if (cached) return cached; // ⚡ instant!
        return fetch(event.request, {mode:'cors'}).then(res => {
          if (res.ok) {
            const clone = res.clone();
            caches.open(CACHE_IMG).then(c => c.put(event.request, clone));
          }
          return res;
        }).catch(() => new Response('', {status: 404}));
      })
    );
    return;
  }

  // HTML PAGES — network first, cache fallback
  if (event.request.mode === 'navigate') {
    event.respondWith(
      fetch(event.request).catch(() => caches.match('/404.html'))
    );
    return;
  }

  // STATIC ASSETS (CSS/JS) — cache first
  event.respondWith(
    caches.match(event.request)
      .then(cached => cached || fetch(event.request).catch(() => {}))
  );
});
